/**供应商表**/
INSERT INTO t_supplier (SUPPLIER_ID, FULL_NAME, ABBR_NAME, CONTACTOR, TEL, EMAIL, QQ)  VALUES ('2001', '上海猫爪信息科技有限公司', '猫爪', '张煦涵','15800495485','','');
INSERT INTO t_supplier (SUPPLIER_ID, FULL_NAME, ABBR_NAME, CONTACTOR, TEL, EMAIL, QQ)  VALUES ('2002', '杭州盼美', '盼美', '','','','');
/**计费通道表 T_PIPLE**/
INSERT INTO t_piple (PIPLE_ID, PIPLE_NAME, SUPPLIER_ID, OP_STATUS, CONTRACT_ID, PIPLE_URL_A,PIPLE_URL_B, NOTIFY_URL_A, NOTIFY_URL_B, CHANNEL_URL_A, CHANNEL_URL_B, PIPLE_DOC, CHANNEL_DOC,PIPLE_AUTH_A, PIPLE_AUTH_B, PIPLE_AUTH_C)
    VALUES ('6001', '猫爪PC页游', '2001', 1, '', 'http://121.199.30.88:9989/pccode/service/getcode', 'http://121.199.30.88:9989/pccode/service/pay', '','', '/mz/getPaySmsForPc', '/mz/smsPay', '','', 'qianya', NULL,NULL);
INSERT INTO t_piple (PIPLE_ID, PIPLE_NAME, SUPPLIER_ID, OP_STATUS, CONTRACT_ID, PIPLE_URL_A,PIPLE_URL_B, NOTIFY_URL_A, NOTIFY_URL_B, CHANNEL_URL_A, CHANNEL_URL_B, PIPLE_DOC, CHANNEL_DOC,PIPLE_AUTH_A, PIPLE_AUTH_B, PIPLE_AUTH_C)
    VALUES ('6011', '盼美沃阅读', '2002', 1, '', 'http://www.linhoo.com.cn/pay-test/iread/getPaySmsTotal', NULL, '/iread/ackTest','', '/iread/getPaySmsTotalP', NULL, '','', 'qianya', NULL,NULL);
/**渠道表 T_CHANNEL**/
INSERT INTO t_channel (CHANNEL_ID, FULL_NAME, ABBR_NAME, CONTRACT_ID, OP_STATUS, CONTACTOR, TEL,EMAIL, QQ, API_KEY, API_PWD)
    VALUES ('1004', '上海悠扬', '上海悠扬', '',1, NULL, NULL, NULL,NULL,'1004', 'B97FED4E9994E33353F2A349853AA8A31428E11BD7AE59');
INSERT INTO t_channel (CHANNEL_ID, FULL_NAME, ABBR_NAME, CONTRACT_ID, OP_STATUS, CONTACTOR, TEL,EMAIL, QQ, API_KEY, API_PWD)
    VALUES ('1005', '焕影', '焕影', '',1,  '', NULL, NULL,NULL,'1005', 'B97FED4E9994E3ABD23466AA8A31428E11BD7AE59');
INSERT INTO t_channel (CHANNEL_ID, FULL_NAME, ABBR_NAME, CONTRACT_ID, OP_STATUS, CONTACTOR, TEL,EMAIL, QQ, API_KEY, API_PWD)
    VALUES ('1003', '千雅联游', '千雅联游',  '',1, NULL, NULL, NULL,NULL,'1005', 'B97FED4E9994E33353DFAA8A31428E11BD7AE59');
/**产品表**/
/**猫爪PC代码子状态清单**/
INSERT INTO T_ORDER_SUBSTATUS VALUES('6001',0,'交易初始化');
INSERT INTO T_ORDER_SUBSTATUS VALUES('6001',1,'获取验证码成功');
INSERT INTO T_ORDER_SUBSTATUS VALUES('6001',2,'获取验证码失败');
INSERT INTO T_ORDER_SUBSTATUS VALUES('6001',3,'支付成功');
INSERT INTO T_ORDER_SUBSTATUS VALUES('6001',4,'支付失败');   
      
      